%YAML 1.2
---
config:
    default: true
    # Allow arbitrary line length
    #
    # Reason: We apply the one-sentence-per-line rule. A sentence may get longer than 80 characters, especially if links are contained.
    #
    # Details: https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md013---line-length
    MD013: false

customRules:
    - "markdownlint-rule-titlecase"

fix: true

noInlineConfig: true

outputFormatters:
    - - markdownlint-cli2-formatter-default
    - - markdownlint-cli2-formatter-junit
